---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-headlamp
  namespace: headlamp
spec:
  chart:
    spec:
      chart: headlamp
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: OCIRepository
        name: podinfo
      version: 0.15.0
  interval: 1m0s
