apiVersion: v1
kind: Namespace
metadata:
  name: grafana
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana-repo
  namespace: grafana
spec:
  interval: 1m0s
  url: https://grafana.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-grafana
  namespace: grafana
spec:
  chart:
    spec:
      chart: grafana
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana-repo
      version: 10.0.0
  interval: 1m0s
