apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: headlamp
        image: headlamp:latest
        ports:
        - containerPort: 4466